### ISSUE TITLE
2 factor authentication caused breakage

### ISSUE THREAD

**Issue by madhephaestus** [CommonWealthRobotics/GithubPasswordManager#1]
When 2fa is enabled on an account, the unit test fails. 

https://github.com/CommonWealthRobotics/GithubPasswordManager/blob/master/GithubPasswordManager/src/test/java/GithubPasswordManager/loginTest.java

To run test:

./gradlew test

the area of code to look at is here:
https://github.com/CommonWealthRobotics/GithubPasswordManager/blob/master/GithubPasswordManager/src/main/java/com/neuronrobotics/bowlerstudio/scripting/PasswordManager.java#L221

**Comment by madhephaestus** [comment]
@Octogonapus I would very much benefit from your help on this one. Do you think you could help me with this using your work-around?

**Comment by Octogonapus** [comment]
Instead of using username + password to log in, BowlerBuilder uses an oauth token. The code to create one and use it to log in is here: https://github.com/CommonWealthRobotics/BowlerBuilder/blob/master/BowlerBuilder/KotlinUI/src/main/kotlin/com/neuronrobotics/bowlerbuilder/controller/gitmenu/LoginManager.kt#L61

**Comment by madhephaestus** [comment]
THis will hopefully be addressed with this PR:

https://github.com/github-api/github-api/issues/602
